# -*- coding: utf-8 -*-
"""2VA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKrGroQrWc-TWHRLPHIoYOU15AC6U7jV
"""

tarefas = [] # Iniciei a lista de tarefa

while True:
    print("\n=================== Menu =============================")
    print("                1. Adicionar uma nova tarefa            ")
    print("                2. Visualizar todas as tarefas          ")
    print("                3. Marcar uma tarda como concluída      ")
    print("                4. Remover uma tarefa                   ")
    print("                5. Sai do programa                      ")

    opcao = int(input("Escolha uma opção:"))  #Solicita uma opção de escolha para o usuário

    if opcao == 1: #Adiciona uma nova tarefa
        tarefa = input("Digite a tarefa: ")
        tarefas.append({"descricao": tarefa, "concluida": False})
        print("Tarefa adicionada com sucesso!")

    elif opcao == 2: #Visualiza todas as tarefas
        print("Tarefas:")
        for i, tarefa in enumerate(tarefas):
            status = "Concluída" if tarefa["concluida"] else "Pendente"
            print(f"{i+1}. {tarefa['descricao']} - {status}")

    elif opcao == 3: #Marca a tarefa como concluída
        tarefa_numero = int(input("Digite o número da tarefa que deseja marcar como concluída: "))
        if tarefa_numero > 0 and tarefa_numero <= len(tarefas):
          tarefas[tarefa_numero - 1]["concluida"] = True
          print("Tarefa marcada como concluida!")
        else:
          print("Tarefa não encontrada!")

    elif opcao == 4: #remove a tarefa
        tarefa_numero = int(input("Digite o número da tarefa que deseja remover do programa: "))
        if tarefa_numero > 0 and tarefa_numero <= len(tarefas):
            del tarefas[tarefa_numero - 1]
            print("Tarefa removida do programa com sucesso")
        else:
            print("Tarefa não encontrada no programa!")

    elif opcao == 5: #Sai do programa
        print("Saindo do Programa Até logo!")
        break

    else: #Informa a opção inválida
        print("Opção inválida. Tente novamente!")